# Generated by Django 3.2.24 on 2024-03-21 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_diary_emotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='content',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='diary',
            name='emotion',
            field=models.CharField(default='', max_length=500),
        ),
    ]
