# Generated by Django 3.2.24 on 2024-03-25 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20240321_1023'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceEmotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.CharField(max_length=500)),
                ('date', models.DateField()),
                ('emotion', models.CharField(default='', max_length=500)),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
