# Generated by Django 3.2.24 on 2024-04-11 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_faceemotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='content',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='diary',
            name='emotion',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.CreateModel(
            name='Tips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('tips', models.CharField(max_length=500)),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
